Repository MakeFrog/TechTalk, pull requests merged in 2024-11, with the labels that each got.

#138 Feat: [영상학습/면접] 영상학습과 면접에 필요한 엔티티 정의
  lib/core/constants/job_group.enum.dart
  lib/features/contents/repositories/contents_repository.dart
  lib/features/contents/repositories/contents_repository_impl.dart
  lib/features/contents/repositories/entities/contents_author_entity.dart
  lib/features/contents/repositories/entities/contents_detail_entity.dart
  lib/features/contents/repositories/entities/contents_overview_entity.dart
  lib/features/contents/repositories/entities/paragraph_entity.dart
  lib/features/contents/repositories/entities/summary_entity.dart
  lib/features/contents/repositories/entities/youtube_video_data_entity.dart
  lib/features/contents/repositories/enums/contents_language.enum.dart
  lib/features/tech_set/data_source/local/tech_set_data_source_impl.dart
  lib/features/tech_set/data_source/local/tech_set_local_data_source.dart
  lib/features/tech_set/repositories/enums/job.enum.dart
  lib/features/tech_set/repositories/tech_set_repository.dart
  lib/features/tech_set/repositories/tech_set_repository_impl.dart
  lib/features/tech_set/tech_set.dart
  lib/features/tech_set/usecases/get_jobs_use_case.dart
  lib/features/topic/repositories/entities/qna_entity.dart
  lib/presentation/pages/sign_up/providers/sign_up_jobs_provider.dart
  lib/presentation/pages/sign_up/providers/sign_up_jobs_provider.g.dart
  pubspec.yaml
Labels: enhancement 🚀

#142 Fix: [OpenAI] OpenAI에서 429 에러 발생시 catch되지 않아 무한로딩 발생하는 현상 해결
  lib/features/chat/use_cases/set_ai_feedback_use_case.dart
Labels: bug 🐛

#149 [채팅 면접] iOS 환경에서 음성 인식 기능이 간헐적으로 작동 안하는 이슈 수정
  lib/app/localization/locale_keys.g.dart
  lib/presentation/pages/interview/chat/providers/speech_to_text_provider.dart
  lib/presentation/pages/interview/chat/widgets/interview_tab_view/rounded_mic_motion_view.dart
  pubspec.lock
  pubspec.yaml
Labels: fix bug 🔧
